### ISSUE TITLE
Explicitly mention the dependency on "libxtend" in the documentation

### ISSUE THREAD

**Issue by niemasd** [auerlab/biolibc#2]
When I tried to compile `biolibc`, I got the following error message:

```
make: *** No rule to make target '../local/lib/include/xtend.h', needed by 'biolibc.o'. Stop.
```

I had no idea what `xtend.h` was from, and I had to use GitHub's general search features, which also weren't super helpful when I searched for `"xtend.h"`, but when I searched for `"xtend\.h"`, it led me to the `libxtend` GitHub repo:

https://github.com/outpaddling/libxtend

It would be good to explicitly include this dependency in the `biolibc` installation instructions

**Comment by outpaddling** [comment]
Thanks for the feedback, Niema!

These libraries are very new and I'm just getting started on proper documentation.  I'll be sure to incorporate your suggestion.

**Comment by outpaddling** [comment]
I updated the README.  Please let me know if anything is still unclear.  Thanks...
